import SearchInput from '@/components/SearchInput';
import { Suspense } from 'react';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Prøveeksamen',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="absolute top-0 w-screen h-20 flex justify-center items-center">
          <Suspense>
            <SearchInput />
          </Suspense>
        </header>
        <main className="mt-[5rem] mb-10">{children}</main>
      </body>
    </html>
  );
}
